version: "3.11"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432
    volumes:
       - config_pgdata:/data/postgres

  adminer:
    image: adminer
    ports:
      - 8080:8080
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate --run-syncdb --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/src
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env

volumes:
  config_pgdata: