# Generated by Django 4.1.6 on 2023-02-04 09:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'original_url',
                    models.URLField(verbose_name='Оригинальная ссылка'),
                ),
                (
                    'short_hash',
                    models.CharField(
                        db_index=True,
                        max_length=6,
                        unique=True,
                        verbose_name='Хеш ссылки',
                    ),
                ),
                (
                    'views_count',
                    models.PositiveIntegerField(
                        default=0, verbose_name='Счётчик переходов по ссылке'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
