# Generated by Django 4.1.6 on 2023-02-03 13:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('url', models.URLField(verbose_name='Ссылка')),
                (
                    'url_hash',
                    models.CharField(
                        db_index=True,
                        max_length=6,
                        unique=True,
                        verbose_name='Хеш ссылки',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Время создания'
                    ),
                ),
                (
                    'views_counter',
                    models.PositiveBigIntegerField(
                        default=0, verbose_name='Счётчик переходов'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
