name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src"
          version: "~= 22.0"